# Site settings
baseURL = "https://claudiaguerreros.github.io/juliososa/"
languageCode = "es-mx"
themesDir="themes"
publishDir="docs"
title = "Fondo Julio Sosa Archivo histórico"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Fondo Julio Sosa Treviño"
  description = "Archivo Histórico Juan Agustín de Espinoza, sj, Universidad Iberoamericana Torreón"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "La página no puede ser localizda"
    text = "Visite esta página [https://claudiaguerreros.github.io/juliososa/]"

  # Navigation Section
  [params.navigation]
    title = "Fotografías"
    subtitle = ""
    menu = "Menú"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Inicio"
      url = "#"

    [[params.navigation.links]]
      name = "Fotografías"
      url = "blogs"

    [[params.navigation.links]]
      name = "J.Sosa"
      url = "blogs/jsosa"

    [[params.navigation.links]]
      name = "Fondo Julio Sosa"
      url = "FondoSosa.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Inicia el recorrido"
      url = "blogs"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Acceso"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Julio Sosa"
    subtitle = "La Laguna en la mirada de Julio Sosa."
    buttonText = "Inicia"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Elvira I"
      subtitle = "Su Majestad Elvira I. Reina del Algodón de 1925. Torreón Coahuila"
      image = "pic11.jpg"
      url = "blogs/elvira"

    [[params.tiles.showcase]]
      title = "Elvira y sus princesas"
      subtitle = "Su Majestad Elvira I Reina del Algodón de 1925. con sus princesas de Torreón, San Pedro, Matamoros, Gómez Palacio y Lerdo Durango. Torreón Coahuila"
      image = "pic12.jpg"
      url = "blogs/princesas"

    [[params.tiles.showcase]]
      title = "Su Majestad Elvira I"
      subtitle = "Su Majestad Elvira I Reina del Algodón de 1925 de pie, Torreón Caoh."
      image = "pic13.jpg"
      url = "blogs/elvira2"

    [[params.tiles.showcase]]
      title = "Chinas poblanas y españolas "
      subtitle = "Sritas que tomaron parte en las fiestas. Grupo en el Casino Feria del algodón . Torreón coahuila"
      image = "pic17.jpg"
      url = "blogs/etnias"

 [[params.tiles.showcase]]
      title = "Capullos"
      subtitle = "Sritas que tomaron parte en las fiestas. Grupo en el Casino Feria del algodón . Torreón coahuila"
      image = "pic19.jpg"
      url = "blogs/capullos"

    [[params.tiles.showcase]]
      title = "Rayos de sol"
      subtitle = "Sritas Rayos de Sol en el Casino Torreón 1925"
      image = "pic20.jpg"
      url = "blogs/rayos"

    
[[params.tiles.showcase]]
      title = "Gotas de agua"
      subtitle = "Gotas de agua. Sritas que tomaron parte en las fiestas. Grupo en el Casino Feria del algodón . Torreón coahuila"
      image = "pic04.jpg"
      url = "blogs/agua"

    [[params.tiles.showcase]]
      title = "Grupo de aguadoras"
      subtitle = "Grupo de aguadoras. Sritas que tomaron parte en las fiestas. Feria del Algodón Torreón Coah. 1925"
      image = "pic07.jpg"
      url = "blogs/aguadoras"

    [[params.tiles.showcase]]
      title = "Crinolinas"
      subtitle = "Crinolinas. Sritas que tomaron parte en las fiestas. Feria del algodón 1925"
      image = "pic01.jpg"
      url = "blogs/crinolinas"
   
    [[params.tiles.showcase]]
      title = "Compañía de Luz"
      subtitle = "Portada que da acceso a la Exposición levantada por la Cia de Luz, Feria del algodón 1925"
      image = "pic06.jpg"
      url = "blogs/luz"

[[params.tiles.showcase]]
      title = "Río Nazas y sus puentes"
      subtitle = "Pabellón de la exposición. Recreación del paisaje lagunero por excelencia"
      image = "pic15.jpg"
      url = "blogs/puentes"

[[params.tiles.showcase]]
      title = "Pabellón de la Jabonera la Esperanza"
      subtitle = "Paisaje lagunero, río de jabón"
      image = "pic16.jpg"
      url = "blogs/jabonera"

[[params.tiles.showcase]]
      title = "Hilados La Fe"
      subtitle = "Stand Hilados y Tejidos La Fe"
      image = "pic21.jpg"
      url = "blogs/hilados"

[[params.tiles.showcase]]
      title = "Cervecería Chihuahua"
      subtitle = "Departamento de la Exposición de la Cervecería Chihuahua"
      image = "pic23.jpg"
      url = "blogs/cerveceria"

[[params.tiles.showcase]]
      title = "Leonor Flores"
      subtitle = "Leonor Flores de Monterrey. NL autora del himno Lagunero Torreón Coahuila 1925"
      image = "pic14.jpg"
      url = "blogs/leonor"

[[params.tiles.showcase]]
      title = "Estudebaker 1925"
      subtitle = "Exhibición del automóvil  EstudebaKer Feria del algodón 1925"
      image = "pic22.jpg"
      url = "blogs/auto"

[[params.tiles.showcase]]
      title = "Charros"
      subtitle = "Grupo de Charros en el Cabaret Feria del Algodón"
      image = "pic24.jpg"
      url = "blogs/charros"
[[params.tiles.showcase]]
      title = "Bodas de Oro"
      subtitle = "Aniversario de bodas pareja españoles"
      image = "pic03.jpg"
      url = "blogs/bodasoro"

[[params.tiles.showcase]]
      title = "Mamá y su bebé"
      subtitle = "Retrato de mamá joven y su pequeña hija"
      image = "pic09.jpg"
      url = "blogs/mamabebe"

[[params.tiles.showcase]]
      title = "Dama en rebozo"
      subtitle = "Retrato de una joven en rebozo"
      image = "pic05.jpg"
      url = "blogs/rebozo"
[[params.tiles.showcase]]
      title = "Charro"
      subtitle = "Charro Lagunero"
      image = "pic26.jpg"
      url = "blogs/charro"
[[params.tiles.showcase]]
      title = "Toro"
      subtitle = "3er premio Boby Nacido en Torreón, 5 años de padres importados Raza Luisa. Edmundo Garza Feria del algodón Torreón Coah. 1925 "
      image = "pic02.jpg"
      url = "blogs/toro"
[[params.tiles.showcase]]
      title = "Novia con sus damas"
      subtitle = "Estudio fotográfico en sepia, la novia y sus damas de compañía "
      image = "pic28.jpg"
      url = "blogs/damas"

[[params.tiles.showcase]]
      title = "Niña con sombrero"
      subtitle = "Estudio fotográfico coloreada al óleo "
      image = "pic32.jpg"
      url = "blogs/nina"

[[params.tiles.showcase]]
      title = "Dama al óleo"
      subtitle = "Estudio fotográfico coloreado al óleo estilo modernista"
      image = "pic30.jpg"
      url = "blogs/color"

[[params.tiles.showcase]]
      title = "Pintura"
      subtitle = "Dama pintada "
      image = "pic29.jpg"
      url = "blogs/pintura"

[[params.tiles.showcase]]
      title = "Quinceañera"
      subtitle = "Estudio a color, quince años "
      image = "pic36.jpg"
      url = "blogs/quince"

[[params.tiles.showcase]]
      title = "Primera comunión"
      subtitle = "Celebración de la primera comunión de un niño"
      image = "pic27.jpg"
      url = "blogs/primera"

[[params.tiles.showcase]]
      title = "Niña en su Primera comunión"
      subtitle = "Celebración de la primera comunión de una niña"
      image = "pic31.jpg"
      url = "blogs/primera2"

[[params.tiles.showcase]]
      title = "Niña"
      subtitle = "Retrato de una niña"
      image = "pic25.jpg"
      url = "blogs/retratonina"

[[params.tiles.showcase]]
      title = "Mujer con aureola"
      subtitle = "Técnica de reservado"
      image = "pic33.jpg"
      url = "blogs/laboratorio"

[[params.tiles.showcase]]
      title = "Señor canoso"
      subtitle = "Manejo de luz, dinamismo en la foto"
      image = "pic34.jpg"
      url = "blogs/movimiento"

[[params.tiles.showcase]]
      title = "Grupo familiar"
      subtitle = "Familia española, estudio clásico"
      image = "pic08.jpg"
      url = "blogs/familia"

[[params.tiles.showcase]]
      title = "Grupo en exterior"
      subtitle = "Con un mando del ejército"
      image = "pic35.jpg"
      url = "blogs/militar"

[[params.tiles.showcase]]
      title = "Foto de boda"
      subtitle = "Novia con su mamá y hermana"
      image = "pic10.jpg"
      url = "blogs/novia"

[[params.tiles.showcase]]
      title = "Niñas"
      subtitle = "Fotografía premiada"
      image = "pic18.jpg"
      url = "blogs/premio"


    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.
 url = "docs/blogs"


# Section Type Two
  [params.two]
    enable = true
    title = "Archivo Histórico"
    subtitle = "Fondo de Julio Sosa"
    


    buttonText = "Inicia"
    url = "blogs"


  
  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Envía un mensaje"
    buttonClear = "Borrar"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "cgsguerrero@gmail.com"

    [[params.contact.phone]]
    title = "Teléfono"
    phone = "(052) 871-7051010"

    [[params.contact.address]]
    title = "Dirección"
    street = "Bulevard Iberoamericana "
    city = "Torreón Coahuila"
    country = "México"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Universidad Iberoamericana Torreón"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
